
version: 2
  jobs:
    build:
      branches:
        only:
          - main
          # - dev
        docker:
          # specify the version you desire here
          - image: circleci/node:8.0
          - image: docker:17.09.1-ce-git  # enable the docker build support
       working_directory: ~/repo
         steps:
           - checkout
           - setup_remote_docker
           # Download and cache dependencies
           - restore_cache:
             keys:
               - v1-dependencies-{{ checksum "package.json" }}
               # fallback to using the latest cache if no exact match is found
               - v1-dependencies-
    
          # clearing the cache
          - run: npm cache clear --force
          # - run: rm package-lock.json
          - run: npm install
          - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
          # run tests!
          # - run: npm run test

          # build the docker image on success
          - run:
            name: Build Success
            when: on_success
            command: |
              docker --version
              docker login -u=triplek254 -p=kelvin97?
              docker build -t ../udagram-api-feed triplek254/udagram-api-feed:latest
              docker build -t ../udagram-api-user triplek254/udagram-api-user:latest
              docker build -t ../udagram-frontend triplek254/udagram-frontend:latest
              docker build -t ../reverseproxy triplek254/reverseproxy:latest


            # docker build -t <docker_account>/<application_name>:$CIRCLE_BRANCH --build-arg MACHINE_NAME=<application_name>-$CIRCLE_BRANCH .
            # docker push <docker_account>/<application_name>:$CIRCLE_BRANCH
              docker push triplek254/udagram-api-feed:latest
              docker push triplek254/reverseproxy:latest
              docker push triplek254/udagram-api-user:latest
              docker push triplek254/udagram-frontend:latest
              echo "Docker build made sucessfully!! for <application_name> $CIRCLE_BRANCH"
          - run:
            name: Build Failure
            when: on_fail
            command: |
              echo "ERROR building <application_name> $CIRCLE_BRANCH





















# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: cimg/node:17.0
#         auth:
#           username: triplek254
#           password: kelvin97? # context / project UI env-var reference
#     environment:
#       CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
#     working_directory: ~/main
#     steps:
#       - run: echo "This is pipeline ID << pipeline.id >>"
#       - run: echo $CIRCLE_COMPARE_URL
   
#       - run: docker login -u=triplek254 -p=kelvin97?
#       - run: docker build -t ../udagram-api-feed triplek254/udagram-api-feed:latest
#       - run: docker build -t ../udagram-api-user triplek254/udagram-api-user:latest
#       - run: docker build -t ../udagram-frontend triplek254/udagram-frontend:latest
#       - run: docker build -t ../reverseproxy triplek254/reverseproxy:latest

#       - run: docker push triplek254/udagram-api-feed:latest
#       - run: docker push triplek254/reverseproxy:latest
#       - run: docker push triplek254/udagram-api-user:latest
#       - run: docker push triplek254/udagram-frontend:latest